### PR TITLE
The latest CloudComPy

### PR DESCRIPTION
**Pull request by prascle**
Hello,
A new CloudComPy release, with some improvements and issues fixed (from #32 to #43).

Have a nice week-end!
Paul

### CODE REVIEW

**Comment by dgirardeau** [comment]
Hi Paul. Should we merge this PR?

**Comment by prascle** [comment]
Hi Daniel, Yes, if that's not a problem for you!
I try to build new binaries every 3 or 4 weeks, and make a pull request with the corresponding sources, so the next set won't be for another 2 or 3 weeks...

I don't know if this is practical for you, let me know if you prefer another organization.
Most of my patches in CloudCompare are only relevant to CloudComPy, some may not build with your process, some are not very clean, so I don't request a pull for them in CloudCompare.
Paul

**Comment by dgirardeau** [comment]
No problem!

**Comment by antoinebio** [comment]
Hello Daniel, Paul,
As LAZ 1.4 is now supported with that new release
have you been able to compute a new SF and stored it as extra byte and save it in LAZ 1.4 ?
I just wanted to know.
test017.py is a example.
(I am sorry if it's not the right place in github to ask that question).
merci
antoine

**Comment by prascle** [comment]
Hello Antoine,
No, it does not work: the saved file does not contain the scalar field. Its name is visible in the CloudCompare dialog, but no scalar field is loaded.
I'm adding this bug to my TODO list.
Thanks for reporting this bug.
Paul

**Pull request merged**
