### PR TITLE
access to colors

### PR DESCRIPTION
**Pull request by prascle**
Hello, 
A new CloudComPy release: 

- colors in ccPointCloud, with access from Numpy.
- Building on Docker on Linux
Paul

### CODE REVIEW

**Comment by dgirardeau** [comment]
Should we merge it?

**Comment by prascle** [comment]
Hello,
Maybe it's better to wait for a new pull request, I am testing new developments.
Paul

**Comment by prascle** [comment]
Hello,
I think it's OK for merge now, with the latest commits from today.
I still have problems with the wrapping of plugins on Windows (M3C2) but it works on Linux.
I will take some time to understand how to do that properly on Windows without rewriting all the plugin...
Thanks,
Paul

**Comment by dgirardeau** [comment]
Ok, let's go then ;)

**Pull request merged**
